### ISSUE TITLE
Dev: Navigation and header

### ISSUE THREAD

**Issue by helms-charity** [mkclawson/impala#2]
https://www.supernaturalimpala.com/

Though there is not currently a mobile navigation, please create one via the Franklin OOTB media queries and OOTB code.

**Comment by meejain** [comment]
Changed to Nav & Hero image pushed to my branch - 

https://branch-meet--impala--mkclawson.hlx.page/Drafts/Meet/

Will check on the space between "Home" & "News & Events" in the nav, further. 

cc @helms-charity @jzachari 

Many Thanks,
