### ISSUE TITLE
Feature: Commenting

### ISSUE THREAD

**Issue by helms-charity** [mkclawson/impala#7]
Blog posts currently have comments. There are a few services that can provide this (we are not creating this native in Franklin in this project). These are the 2 free services that Mike should consider:
- https://disqus.com/
- https://developers.facebook.com/docs/plugins/comments/ 

TODO: implement the best one.

**Comment by jzachari** [comment]
Mike is leaving the decision up to us on which one to use.  Having comments on blog posts is needed.

**Comment by helms-charity** [comment]
OK, i'm going with Disqus after reading https://raventools.com/blog/facebook-comments/ .

**Comment by helms-charity** [comment]
I have copied down all the raw embed code after signing up for a free disqus account, it is my drafts folder.
